import {
  configureStore,
  bindActionCreators,
  combineReducers,
  applyMiddleware,
  Tuple,
} from "@reduxjs/toolkit";
import { createLogger } from "redux-logger";
// initializing the redux logger
const logger = createLogger();

type OrderCakeActionType = {
  type: "CAKE_ORDERED";
  payload: number;
};
type RestockCakeActionType = {
  type: "CAKE_RESTOCKED";
  payload: number;
};

type OrderIceCreamActionType = {
  type: "ICE_CREAM_ORDERED";
  payload: number;
};
type RestockIceCreamAction = {
  type: "ICE_CREAM_RESTOCKED";
  payload: number;
};

function orderCake(): OrderCakeActionType {
  return {
    type: "CAKE_ORDERED",
    payload: 1,
  };
}

function restockCake(payload: number = 1): RestockCakeActionType {
  return {
    type: "CAKE_RESTOCKED",
    payload,
  };
}

function orderIceCream(quantity = 1): OrderIceCreamActionType {
  return {
    type: "ICE_CREAM_ORDERED",
    payload: quantity,
  };
}
function restockIceCream(quantity = 1): RestockIceCreamAction {
  return {
    type: "ICE_CREAM_RESTOCKED",
    payload: quantity,
  };
}

type CakeActionType = OrderCakeActionType | RestockCakeActionType;

type IceCreamActionType =
  | OrderIceCreamActionType
  | RestockIceCreamAction
  | OrderCakeActionType;

const initialCakeState = {
  numOfCakes: 10,
};

const cakeReducer = (
  state = initialCakeState,
  action: CakeActionType
): typeof initialCakeState => {
  switch (action.type) {
    case "CAKE_ORDERED":
      return {
        ...state,
        numOfCakes: state.numOfCakes - action.payload,
      };
    case "CAKE_RESTOCKED":
      return {
        ...state,
        numOfCakes: state.numOfCakes + action.payload,
      };
    default:
      return state;
  }
};

const initialIceCreamState = {
  numOfIceCreams: 20,
};

const iceCreamReducer = (
  state = initialIceCreamState,
  action: IceCreamActionType
): typeof initialIceCreamState => {
  switch (action.type) {
    case "ICE_CREAM_ORDERED":
      return {
        ...state,
        numOfIceCreams: state.numOfIceCreams - action.payload,
      };
    case "ICE_CREAM_RESTOCKED":
      return {
        ...state,
        numOfIceCreams: state.numOfIceCreams + action.payload,
      };
    // we have 2 separate reducers but when we dispatch an action both the reducers receives that action one of them act on that action where else the other ignores it.
    // Let's take example for our application let's say that we want to reward our customers, for every cake they buy we want to give them an ice cream for free
    // To active that we will going to add another case where we will check for the cake ordered
    case "CAKE_ORDERED":
      // so, when the cake is ordered the 'cakeReducer' will decrements the cake by one, however the 'iceCreamReducer' response to the same action and reduces number of iceCream by 1
      return {
        ...state,
        numOfIceCreams: state.numOfIceCreams - 1,
      };
    // Important points:
    // Each reducers update it's portion of it's application state, however it can response to any action dispatch in the application
    // But that is not what will happen with redux toolkit, by default the reducer from one Slice will only response to the action type generated by the same slice
    // If you want to response action generate by other Slice beside the action types it has generated you need to make use of extra reducer
    // Extra reducer are the addition reducer apart from the reducer generate by 'createSlice'
    // Created extra reducers inside '../02_With_Redux_Toolkit/features/icecream/iceCreamSlice.ts'
    // https://redux-toolkit.js.org/rtk-query/usage/examples#using-extrareducers
    // https://redux-toolkit.js.org/api/createslice#extrareducers
    default:
      return state;
  }
};

const rootReducer = combineReducers({
  cake: cakeReducer,
  iceCream: iceCreamReducer,
});

const store = configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) => {
    return getDefaultMiddleware().concat(logger as any);
  },
});

// console.log("Initial State: ", store.getState());

const unsubscribe = store.subscribe(() => {
  // console.log("Updated State: ", store.getState());
});

const actions = bindActionCreators(
  { orderCake, restockCake, orderIceCream, restockIceCream },
  store.dispatch
);

actions.orderCake();
actions.orderCake();
actions.orderCake();
actions.restockCake(3);

actions.orderIceCream();
actions.orderIceCream();
actions.restockIceCream(2);

unsubscribe();
